// Renders public/icon.svg and public/icon-maskable.svg into the PNG sizes the
// install prompts want, plus a favicon. Run it after editing either SVG:
//
//   npm run icons
//
// The output is committed, so neither `next build` nor a Vercel deploy needs
// rsvg-convert installed — only whoever edits the mark does.
//
//   brew install librsvg   # rsvg-convert
//
import { execFile } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import { promisify } from 'node:util'

const run = promisify(execFile)

const OUT = 'public/icons'
const JOBS = [
  // `any` icons sit on their own rounded ground; the launcher does not crop them.
  { src: 'public/icon.svg', size: 192, out: 'icon-192.png' },
  { src: 'public/icon.svg', size: 512, out: 'icon-512.png' },
  // iOS ignores the manifest and reads apple-touch-icon, always at 180px, and
  // composites it on its own rounded rect — so the `any` art is the right one.
  { src: 'public/icon.svg', size: 180, out: 'apple-touch-icon.png' },
  // Android crops these, so they come from the padded, full-bleed source.
  { src: 'public/icon-maskable.svg', size: 192, out: 'icon-maskable-192.png' },
  { src: 'public/icon-maskable.svg', size: 512, out: 'icon-maskable-512.png' },
]

async function which(cmd) {
  try {
    await run('sh', ['-c', `command -v ${cmd}`])
    return true
  } catch {
    return false
  }
}

const haveRsvg = await which('rsvg-convert')
const haveMagick = await which('magick')
if (!haveRsvg && !haveMagick) {
  console.error('Need rsvg-convert (brew install librsvg) or magick to render the SVGs.')
  process.exit(1)
}

await mkdir(OUT, { recursive: true })

for (const { src, size, out } of JOBS) {
  const dest = `${OUT}/${out}`
  if (haveRsvg) {
    // -w/-h rather than -z: the source viewBox is 512 and every target is a
    // different square, so scaling by factor would need per-job arithmetic.
    await run('rsvg-convert', ['-w', String(size), '-h', String(size), '-o', dest, src])
  } else {
    await run('magick', ['-background', 'none', '-density', '384', src, '-resize', `${size}x${size}`, dest])
  }
  console.log(`${dest}  ${size}x${size}`)
}

// A multi-resolution .ico for browser tabs and Windows pinning. ImageMagick
// only; rsvg-convert cannot write ICO, and the existing favicon.ico stays put
// if it is missing.
if (haveMagick) {
  await run('magick', [
    'public/icon.svg',
    '-background', 'none',
    '-define', 'icon:auto-resize=16,32,48,64,128,256',
    'src/app/favicon.ico',
  ])
  console.log('src/app/favicon.ico  16..256')
} else {
  console.log('skipped favicon.ico (needs magick)')
}

// Written next to the PNGs so a stale set is obvious in a diff.
await writeFile(`${OUT}/README.md`, 'Generated by `npm run icons` from public/icon.svg and public/icon-maskable.svg. Do not edit by hand.\n')
